version: '3.8'
services:
  vue-fintech:
    build:
      context: .
      dockerfile: DockerFile
    container_name: next-curriculum-vitae-aziz-anwar
    restart: unless-stopped
    networks:
      private-network:
        ipv4_address: 172.18.0.7
    # default port 80

networks:
  private-network:
    name: private-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
